[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
welds = { version = "0.4.16", features = ["sqlite", "migrations"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls","tls-rustls", "sqlite", "chrono", "uuid"] }
tokio = "1.45.1"
