[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
welds = { version = "0.4.16", features = ["sqlite", "migrations",] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls","tls-rustls", "sqlite", "chrono", "uuid"] }
once_cell = "1.21.3"
tokio = { version="1.46.0", features = ["full"] } 
uuid = { version = "1.1.2", features = ["v4"] }

[features]
desktop = []
server = []
