[workspace]
resolver = "2"
members = [
    "ui",
    "web",
    "desktop",
    "mobile",
    "api",
]

[workspace.dependencies]
dioxus = "=0.7.0-alpha.2"
dioxus-primitives = {git = "https://github.com/DioxusLabs/components" }

# workspace
ui = { path = "ui" }
api = { path = "api" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[patch.crates-io]
dioxus-geolocation = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-notification = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-sdk = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus_storage = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-sync = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-time = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-util = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
dioxus-window = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }
