default_job = "clippy-server"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy-server]
command = ["cargo", "clippy", "--package", "web", "--features", "server"]
need_stdout = false

[jobs.clippy-client]
command = ["cargo", "clippy", "--package", "web", "--features", "web"]
need_stdout = false

[keybindings]
s = "job:clippy-server"
c = "job:clippy-client"
