//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "import_rows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub data: String,
    pub hash: String,
    pub import_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::import::Entity",
        from = "Column::ImportId",
        to = "super::import::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Import,
}

impl Related<super::import::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Import.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
